source 'https://rubygems.org'

gem 'rails', '3.2.12'
gem 'sqlite3', '1.3.7'
gem 'haml-rails', '0.3.4'

group :assets do
  gem 'sass-rails', '3.2.5'
  gem 'coffee-rails', '3.2.2'
  gem 'uglifier', '1.0.3'
end

gem 'jquery-rails', '2.0.2'
gem 'backbone-on-rails', '0.9.2.1'

group :development do
end

qlive_gems_path = File.expand_path('../../../..', __FILE__)

group :test, :development do
  gem 'factory_girl_rails', '3.5.0'
  gem 'qlive', :path => "#{qlive_gems_path}/qlive"
  gem 'qlive-rails', :path => "#{qlive_gems_path}/qlive-rails", :require => 'qlive/engine'
  gem 'qlive-rspec', :path => "#{qlive_gems_path}/qlive-rspec"
end

group :test do
  gem 'rspec-rails', '2.13.0'
  gem 'poltergeist', '1.1.2'
end
